language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script: vendor/bin/phing

notifications:
  email:
    - mail+travis-php-analyzer@markus.fischer.name
