<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension bcmath
function bcadd($left_operand, $right_operand, $scale) {}
function bcsub($left_operand, $right_operand, $scale) {}
function bcmul($left_operand, $right_operand, $scale) {}
function bcdiv($left_operand, $right_operand, $scale) {}
function bcmod($left_operand, $right_operand) {}
function bcpow($x, $y, $scale) {}
function bcsqrt($operand, $scale) {}
function bcscale($scale) {}
function bccomp($left_operand, $right_operand, $scale) {}
function bcpowmod($x, $y, $mod, $scale) {}
