<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension bz2
function bzopen($file, $mode) {}
function bzread($bz, $length) {}
function bzwrite($fp, $str, $length) {}
function bzflush($fp) {}
function bzclose($fp) {}
function bzerrno($bz) {}
function bzerrstr($bz) {}
function bzerror($bz) {}
function bzcompress($source, $blocksize, $workfactor) {}
function bzdecompress($source, $small) {}
