<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension calendar
function jdtogregorian($juliandaycount) {}
function gregoriantojd($month, $day, $year) {}
function jdtojulian($juliandaycount) {}
function juliantojd($month, $day, $year) {}
function jdtojewish($juliandaycount, $hebrew, $fl) {}
function jewishtojd($month, $day, $year) {}
function jdtofrench($juliandaycount) {}
function frenchtojd($month, $day, $year) {}
function jddayofweek($juliandaycount, $mode) {}
function jdmonthname($juliandaycount, $mode) {}
function easter_date($year) {}
function easter_days($year, $method) {}
function unixtojd($timestamp) {}
function jdtounix($jday) {}
function cal_to_jd($calendar, $month, $day, $year) {}
function cal_from_jd($jd, $calendar) {}
function cal_days_in_month($calendar, $month, $year) {}
function cal_info($calendar) {}
