<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension ctype
function ctype_alnum($text) {}
function ctype_alpha($text) {}
function ctype_cntrl($text) {}
function ctype_digit($text) {}
function ctype_lower($text) {}
function ctype_graph($text) {}
function ctype_print($text) {}
function ctype_punct($text) {}
function ctype_space($text) {}
function ctype_upper($text) {}
function ctype_xdigit($text) {}
