<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension curl
function curl_init($url) {}
function curl_copy_handle($ch) {}
function curl_version($version) {}
function curl_setopt($ch, $option, $value) {}
function curl_setopt_array($ch, array $options) {}
function curl_exec($ch) {}
function curl_getinfo($ch, $option) {}
function curl_error($ch) {}
function curl_errno($ch) {}
function curl_close($ch) {}
function curl_multi_init() {}
function curl_multi_add_handle($mh, $ch) {}
function curl_multi_remove_handle($mh, $ch) {}
function curl_multi_select($mh, $timeout) {}
function curl_multi_exec($mh, &$still_running) {}
function curl_multi_getcontent($ch) {}
function curl_multi_info_read($mh, &$msgs_in_queue) {}
function curl_multi_close($mh) {}
