<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension dba
function dba_open($path, $mode, $handlername, $param4) {}
function dba_popen($path, $mode, $handlername, $param4) {}
function dba_close($handle) {}
function dba_delete($key, $handle) {}
function dba_exists($key, $handle) {}
function dba_fetch($key, $skip, $handle) {}
function dba_insert($key, $value, $handle) {}
function dba_replace($key, $value, $handle) {}
function dba_firstkey($handle) {}
function dba_nextkey($handle) {}
function dba_optimize($handle) {}
function dba_sync($handle) {}
function dba_handlers($full_info) {}
function dba_list() {}
function dba_key_split($key) {}
