<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension ereg
function ereg($pattern, $string, &$registers) {}
function ereg_replace($pattern, $replacement, $string) {}
function eregi($pattern, $string, &$registers) {}
function eregi_replace($pattern, $replacement, $string) {}
function split($pattern, $string, $limit) {}
function spliti($pattern, $string, $limit) {}
function sql_regcase($string) {}
