<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension exif 1.4 $Id$
function exif_read_data($filename, $sections_needed, $sub_arrays, $read_thumbnail) {}
function read_exif_data($filename, $sections_needed, $sub_arrays, $read_thumbnail) {}
function exif_tagname($index) {}
function exif_thumbnail($filename, &$width, &$height, &$imagetype) {}
function exif_imagetype($imagefile) {}
