<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension fileinfo 1.0.5
function finfo_open($options, $arg) {}
function finfo_close($finfo) {}
function finfo_set_flags($finfo, $options) {}
function finfo_file($finfo, $filename, $options, $context) {}
function finfo_buffer($finfo, $string, $options, $context) {}
function mime_content_type($string) {}
class finfo{
  public function finfo($options, $arg) {}
  public function set_flags($options) {}
  public function file($filename, $options, $context) {}
  public function buffer($string, $options, $context) {}
}
