<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension filter 0.11.0
function filter_input($type, $variable_name, $filter, $options) {}
function filter_var($variable, $filter, $options) {}
function filter_input_array($type, $definition, $add_empty) {}
function filter_var_array($data, $definition, $add_empty) {}
function filter_list() {}
function filter_has_var($type, $variable_name) {}
function filter_id($filtername) {}
