<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension ftp
function ftp_connect($host, $port, $timeout) {}
function ftp_ssl_connect($host, $port, $timeout) {}
function ftp_login($ftp, $username, $password) {}
function ftp_pwd($ftp) {}
function ftp_cdup($ftp) {}
function ftp_chdir($ftp, $directory) {}
function ftp_exec($ftp, $command) {}
function ftp_raw($ftp, $command) {}
function ftp_mkdir($ftp, $directory) {}
function ftp_rmdir($ftp, $directory) {}
function ftp_chmod($ftp, $mode, $filename) {}
function ftp_alloc($ftp, $size, &$response) {}
function ftp_nlist($ftp, $directory) {}
function ftp_rawlist($ftp, $directory, $recursive) {}
function ftp_systype($ftp) {}
function ftp_pasv($ftp, $pasv) {}
function ftp_get($ftp, $local_file, $remote_file, $mode, $resume_pos) {}
function ftp_fget($ftp, $fp, $remote_file, $mode, $resumepos) {}
function ftp_put($ftp, $remote_file, $local_file, $mode, $startpos) {}
function ftp_fput($ftp, $remote_file, $fp, $mode, $startpos) {}
function ftp_size($ftp, $filename) {}
function ftp_mdtm($ftp, $filename) {}
function ftp_rename($ftp, $src, $dest) {}
function ftp_delete($ftp, $file) {}
function ftp_site($ftp, $cmd) {}
function ftp_close($ftp) {}
function ftp_set_option($ftp, $option, $value) {}
function ftp_get_option($ftp, $option) {}
function ftp_nb_fget($ftp, $fp, $remote_file, $mode, $resumepos) {}
function ftp_nb_get($ftp, $local_file, $remote_file, $mode, $resume_pos) {}
function ftp_nb_continue($ftp) {}
function ftp_nb_put($ftp, $remote_file, $local_file, $mode, $startpos) {}
function ftp_nb_fput($ftp, $remote_file, $fp, $mode, $startpos) {}
function ftp_quit($ftp) {}
