<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension gd
function gd_info() {}
function imagearc($im, $cx, $cy, $w, $h, $s, $e, $col) {}
function imageellipse($im, $cx, $cy, $w, $h, $color) {}
function imagechar($im, $font, $x, $y, $c, $col) {}
function imagecharup($im, $font, $x, $y, $c, $col) {}
function imagecolorat($im, $x, $y) {}
function imagecolorallocate($im, $red, $green, $blue) {}
function imagepalettecopy($dst, $src) {}
function imagecreatefromstring($image) {}
function imagecolorclosest($im, $red, $green, $blue) {}
function imagecolorclosesthwb($im, $red, $green, $blue) {}
function imagecolordeallocate($im, $index) {}
function imagecolorresolve($im, $red, $green, $blue) {}
function imagecolorexact($im, $red, $green, $blue) {}
function imagecolorset($im, $color, $red, $green, $blue, $alpha) {}
function imagecolortransparent($im, $col) {}
function imagecolorstotal($im) {}
function imagecolorsforindex($im, $index) {}
function imagecopy($dst_im, $src_im, $dst_x, $dst_y, $src_x, $src_y, $src_w, $src_h) {}
function imagecopymerge($src_im, $dst_im, $dst_x, $dst_y, $src_x, $src_y, $src_w, $src_h, $pct) {}
function imagecopymergegray($src_im, $dst_im, $dst_x, $dst_y, $src_x, $src_y, $src_w, $src_h, $pct) {}
function imagecopyresized($dst_im, $src_im, $dst_x, $dst_y, $src_x, $src_y, $dst_w, $dst_h, $src_w, $src_h) {}
function imagecreate($x_size, $y_size) {}
function imagecreatetruecolor($x_size, $y_size) {}
function imageistruecolor($im) {}
function imagetruecolortopalette($im, $ditherFlag, $colorsWanted) {}
function imagesetthickness($im, $thickness) {}
function imagefilledarc($im, $cx, $cy, $w, $h, $s, $e, $col, $style) {}
function imagefilledellipse($im, $cx, $cy, $w, $h, $color) {}
function imagealphablending($im, $blend) {}
function imagesavealpha($im, $save) {}
function imagecolorallocatealpha($im, $red, $green, $blue, $alpha) {}
function imagecolorresolvealpha($im, $red, $green, $blue, $alpha) {}
function imagecolorclosestalpha($im, $red, $green, $blue, $alpha) {}
function imagecolorexactalpha($im, $red, $green, $blue, $alpha) {}
function imagecopyresampled($dst_im, $src_im, $dst_x, $dst_y, $src_x, $src_y, $dst_w, $dst_h, $src_w, $src_h) {}
function imagerotate($im, $angle, $bgdcolor, $ignoretransparent) {}
function imageantialias($im, $on) {}
function imagesettile($im, $tile) {}
function imagesetbrush($im, $brush) {}
function imagesetstyle($im, $styles) {}
function imagecreatefrompng($filename) {}
function imagecreatefromgif($filename) {}
function imagecreatefromjpeg($filename) {}
function imagecreatefromwbmp($filename) {}
function imagecreatefromxbm($filename) {}
function imagecreatefromgd($filename) {}
function imagecreatefromgd2($filename) {}
function imagecreatefromgd2part($filename, $srcX, $srcY, $width, $height) {}
function imagepng($im, $filename) {}
function imagegif($im, $filename) {}
function imagejpeg($im, $filename, $quality) {}
function imagewbmp($im, $filename, $foreground) {}
function imagegd($im, $filename) {}
function imagegd2($im, $filename, $chunk_size, $type) {}
function imagedestroy($im) {}
function imagegammacorrect($im, $inputgamma, $outputgamma) {}
function imagefill($im, $x, $y, $col) {}
function imagefilledpolygon($im, $points, $num_pos, $col) {}
function imagefilledrectangle($im, $x1, $y1, $x2, $y2, $col) {}
function imagefilltoborder($im, $x, $y, $border, $col) {}
function imagefontwidth($font) {}
function imagefontheight($font) {}
function imageinterlace($im, $interlace) {}
function imageline($im, $x1, $y1, $x2, $y2, $col) {}
function imageloadfont($filename) {}
function imagepolygon($im, $points, $num_pos, $col) {}
function imagerectangle($im, $x1, $y1, $x2, $y2, $col) {}
function imagesetpixel($im, $x, $y, $col) {}
function imagestring($im, $font, $x, $y, $str, $col) {}
function imagestringup($im, $font, $x, $y, $str, $col) {}
function imagesx($im) {}
function imagesy($im) {}
function imagedashedline($im, $x1, $y1, $x2, $y2, $col) {}
function imagettfbbox($size, $angle, $font_file, $text) {}
function imagettftext($im, $size, $angle, $x, $y, $col, $font_file, $text) {}
function imageftbbox($size, $angle, $font_file, $text, $extrainfo) {}
function imagefttext($im, $size, $angle, $x, $y, $col, $font_file, $text, $extrainfo) {}
function imagetypes() {}
function jpeg2wbmp($f_org, $f_dest, $d_height, $d_width, $d_threshold) {}
function png2wbmp($f_org, $f_dest, $d_height, $d_width, $d_threshold) {}
function image2wbmp($im, $filename, $threshold) {}
function imagelayereffect($im, $effect) {}
function imagexbm($im, $filename, $foreground) {}
function imagecolormatch($im1, $im2) {}
function imagefilter($im, $filtertype, $arg1, $arg2, $arg3, $arg4) {}
function imageconvolution($im, $matrix3x3, $div, $offset) {}
