<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension hash 1.0
function hash($algo, $data, $raw_output) {}
function hash_file($algo, $filename, $raw_output) {}
function hash_hmac($algo, $data, $key, $raw_output) {}
function hash_hmac_file($algo, $filename, $key, $raw_output) {}
function hash_init($algo, $options, $key) {}
function hash_update($context, $data) {}
function hash_update_stream($context, $handle, $length) {}
function hash_update_file($context, $filename, $context) {}
function hash_final($context, $raw_output) {}
function hash_copy($context) {}
function hash_algos() {}
