<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension iconv
function iconv($in_charset, $out_charset, $str) {}
function iconv_get_encoding($type) {}
function iconv_set_encoding($type, $charset) {}
function iconv_strlen($str, $charset) {}
function iconv_substr($str, $offset, $length, $charset) {}
function iconv_strpos($haystack, $needle, $offset, $charset) {}
function iconv_strrpos($haystack, $needle, $charset) {}
function iconv_mime_encode($field_name, $field_value, $preference) {}
function iconv_mime_decode($encoded_string, $mode, $charset) {}
function iconv_mime_decode_headers($headers, $mode, $charset) {}
