<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension json 1.2.1
function json_encode($value, $options) {}
function json_decode($json, $assoc, $depth, $options) {}
function json_last_error() {}
interface JsonSerializable{
  public function jsonSerialize() {}
}
