<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension ldap
function ldap_connect($hostname, $port) {}
function ldap_close($link_identifier) {}
function ldap_bind($link_identifier, $bind_rdn, $bind_password) {}
function ldap_sasl_bind($link, $binddn, $password, $sasl_mech, $sasl_realm, $sasl_authz_id, $props) {}
function ldap_unbind($link_identifier) {}
function ldap_read($link_identifier, $base_dn, $filter, $attributes, $attrsonly, $sizelimit, $timelimit, $deref) {}
function ldap_list($link_identifier, $base_dn, $filter, $attributes, $attrsonly, $sizelimit, $timelimit, $deref) {}
function ldap_search($link_identifier, $base_dn, $filter, $attributes, $attrsonly, $sizelimit, $timelimit, $deref) {}
function ldap_free_result($link_identifier) {}
function ldap_count_entries($link_identifier, $result_identifier) {}
function ldap_first_entry($link_identifier, $result_identifier) {}
function ldap_next_entry($link_identifier, $result_identifier) {}
function ldap_get_entries($link_identifier, $result_identifier) {}
function ldap_first_attribute($link_identifier, $result_entry_identifier) {}
function ldap_next_attribute($link_identifier, $result_entry_identifier) {}
function ldap_get_attributes($link_identifier, $result_entry_identifier) {}
function ldap_get_values($link_identifier, $result_entry_identifier, $attribute) {}
function ldap_get_values_len($link_identifier, $result_entry_identifier, $attribute) {}
function ldap_get_dn($link_identifier, $result_entry_identifier) {}
function ldap_explode_dn($dn, $with_attrib) {}
function ldap_dn2ufn($dn) {}
function ldap_add($link_identifier, $dn, $entry) {}
function ldap_delete($link_identifier, $dn) {}
function ldap_modify_batch($link_identifier, $dn, array $modifications_info) {}
function ldap_modify($link_identifier, $dn, $entry) {}
function ldap_mod_add($link_identifier, $dn, $entry) {}
function ldap_mod_replace($link_identifier, $dn, $entry) {}
function ldap_mod_del($link_identifier, $dn, $entry) {}
function ldap_errno($link_identifier) {}
function ldap_err2str($errno) {}
function ldap_error($link_identifier) {}
function ldap_compare($link_identifier, $dn, $attribute, $value) {}
function ldap_sort($link, $result, $sortfilter) {}
function ldap_rename($link_identifier, $dn, $newrdn, $newparent, $deleteoldrdn) {}
function ldap_get_option($link_identifier, $option, &$retval) {}
function ldap_set_option($link_identifier, $option, $newval) {}
function ldap_first_reference($link, $result) {}
function ldap_next_reference($link, $entry) {}
function ldap_parse_reference($link, $entry, &$referrals) {}
function ldap_parse_result($link, $result, &$errcode, &$matcheddn, &$errmsg, &$referrals) {}
function ldap_start_tls($link_identifier) {}
function ldap_set_rebind_proc($link, $callback) {}
function ldap_control_paged_result($link, $pagesize, $iscritical, $cookie) {}
function ldap_control_paged_result_response($link, $result, &$cookie, &$estimated) {}
