<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension libxml
function libxml_set_streams_context($context) {}
function libxml_use_internal_errors($use_errors) {}
function libxml_get_last_error() {}
function libxml_clear_errors() {}
function libxml_get_errors() {}
function libxml_disable_entity_loader($disable) {}
function libxml_set_external_entity_loader($resolver_function) {}
class LibXMLError{
}
