<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension mbstring
function mb_convert_case($sourcestring, $mode, $encoding) {}
function mb_strtoupper($sourcestring, $encoding) {}
function mb_strtolower($sourcestring, $encoding) {}
function mb_language($language) {}
function mb_internal_encoding($encoding) {}
function mb_http_input($type) {}
function mb_http_output($encoding) {}
function mb_detect_order($encoding) {}
function mb_substitute_character($substchar) {}
function mb_parse_str($encoded_string, &$result) {}
function mb_output_handler($contents, $status) {}
function mb_preferred_mime_name($encoding) {}
function mb_strlen($str, $encoding) {}
function mb_strpos($haystack, $needle, $offset, $encoding) {}
function mb_strrpos($haystack, $needle, $offset, $encoding) {}
function mb_stripos($haystack, $needle, $offset, $encoding) {}
function mb_strripos($haystack, $needle, $offset, $encoding) {}
function mb_strstr($haystack, $needle, $part, $encoding) {}
function mb_strrchr($haystack, $needle, $part, $encoding) {}
function mb_stristr($haystack, $needle, $part, $encoding) {}
function mb_strrichr($haystack, $needle, $part, $encoding) {}
function mb_substr_count($haystack, $needle, $encoding) {}
function mb_substr($str, $start, $length, $encoding) {}
function mb_strcut($str, $start, $length, $encoding) {}
function mb_strwidth($str, $encoding) {}
function mb_strimwidth($str, $start, $width, $trimmarker, $encoding) {}
function mb_convert_encoding($str, $to, $from) {}
function mb_detect_encoding($str, $encoding_list, $strict) {}
function mb_list_encodings() {}
function mb_encoding_aliases($encoding) {}
function mb_convert_kana($str, $option, $encoding) {}
function mb_encode_mimeheader($str, $charset, $transfer, $linefeed, $indent) {}
function mb_decode_mimeheader($string) {}
function mb_convert_variables($to, $from, &$param3) {}
function mb_encode_numericentity($string, $convmap, $encoding, $is_hex) {}
function mb_decode_numericentity($string, $convmap, $encoding) {}
function mb_send_mail($to, $subject, $message, $additional_headers, $additional_parameters) {}
function mb_get_info($type) {}
function mb_check_encoding($var, $encoding) {}
function mb_regex_encoding($encoding) {}
function mb_regex_set_options($options) {}
function mb_ereg($pattern, $string, &$registers) {}
function mb_eregi($pattern, $string, &$registers) {}
function mb_ereg_replace($pattern, $replacement, $string, $option) {}
function mb_eregi_replace($pattern, $replacement, $string) {}
function mb_ereg_replace_callback($pattern, $callback, $string, $option) {}
function mb_split($pattern, $string, $limit) {}
function mb_ereg_match($pattern, $string, $option) {}
function mb_ereg_search($pattern, $option) {}
function mb_ereg_search_pos($pattern, $option) {}
function mb_ereg_search_regs($pattern, $option) {}
function mb_ereg_search_init($string, $pattern, $option) {}
function mb_ereg_search_getregs() {}
function mb_ereg_search_getpos() {}
function mb_ereg_search_setpos($position) {}
function mbregex_encoding($encoding) {}
function mbereg($pattern, $string, &$registers) {}
function mberegi($pattern, $string, &$registers) {}
function mbereg_replace($pattern, $replacement, $string, $option) {}
function mberegi_replace($pattern, $replacement, $string) {}
function mbsplit($pattern, $string, $limit) {}
function mbereg_match($pattern, $string, $option) {}
function mbereg_search($pattern, $option) {}
function mbereg_search_pos($pattern, $option) {}
function mbereg_search_regs($pattern, $option) {}
function mbereg_search_init($string, $pattern, $option) {}
function mbereg_search_getregs() {}
function mbereg_search_getpos() {}
function mbereg_search_setpos($position) {}
