<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension openssl
function openssl_pkey_free($key) {}
function openssl_pkey_new($configargs) {}
function openssl_pkey_export($key, &$out, $passphrase, $config_args) {}
function openssl_pkey_export_to_file($key, $outfilename, $passphrase, $config_args) {}
function openssl_pkey_get_private($key, $passphrase) {}
function openssl_pkey_get_public($cert) {}
function openssl_pkey_get_details($key) {}
function openssl_free_key($key) {}
function openssl_get_privatekey($key, $passphrase) {}
function openssl_get_publickey($cert) {}
function openssl_x509_read($cert) {}
function openssl_x509_free($x509) {}
function openssl_x509_parse($x509, $shortname) {}
function openssl_x509_checkpurpose($x509cert, $purpose, $cainfo, $untrustedfile) {}
function openssl_x509_check_private_key($cert, $key) {}
function openssl_x509_export($x509, &$out, $notext) {}
function openssl_x509_export_to_file($x509, $outfilename, $notext) {}
function openssl_pkcs12_export($x509, &$out, $priv_key, $pass, $args) {}
function openssl_pkcs12_export_to_file($x509, $filename, $priv_key, $pass, $args) {}
function openssl_pkcs12_read($PKCS12, &$certs, $pass) {}
function openssl_csr_new($dn, &$privkey, $configargs, $extraattribs) {}
function openssl_csr_export($csr, &$out, $notext) {}
function openssl_csr_export_to_file($csr, $outfilename, $notext) {}
function openssl_csr_sign($csr, $x509, $priv_key, $days, $config_args, $serial) {}
function openssl_csr_get_subject($csr) {}
function openssl_csr_get_public_key($csr) {}
function openssl_digest($data, $method, $raw_output) {}
function openssl_encrypt($data, $method, $password, $options, $iv) {}
function openssl_decrypt($data, $method, $password, $options, $iv) {}
function openssl_cipher_iv_length($method) {}
function openssl_sign($data, &$signature, $key, $method) {}
function openssl_verify($data, $signature, $key, $method) {}
function openssl_seal($data, &$sealdata, &$ekeys, $pubkeys) {}
function openssl_open($data, &$opendata, $ekey, $privkey) {}
function openssl_pkcs7_verify($filename, $flags, $signerscerts, $cainfo, $extracerts, $content) {}
function openssl_pkcs7_decrypt($infilename, $outfilename, $recipcert, $recipkey) {}
function openssl_pkcs7_sign($infile, $outfile, $signcert, $signkey, $headers, $flags, $extracertsfilename) {}
function openssl_pkcs7_encrypt($infile, $outfile, $recipcerts, $headers, $flags, $cipher) {}
function openssl_private_encrypt($data, &$crypted, $key, $padding) {}
function openssl_private_decrypt($data, &$crypted, $key, $padding) {}
function openssl_public_encrypt($data, &$crypted, $key, $padding) {}
function openssl_public_decrypt($data, &$crypted, $key, $padding) {}
function openssl_get_md_methods($aliases) {}
function openssl_get_cipher_methods($aliases) {}
function openssl_dh_compute_key($pub_key, $dh_key) {}
function openssl_random_pseudo_bytes($length, &$result_is_strong) {}
function openssl_error_string() {}
