<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension pcre
function preg_match($pattern, $subject, &$subpatterns, $flags, $offset) {}
function preg_match_all($pattern, $subject, &$subpatterns, $flags, $offset) {}
function preg_replace($regex, $replace, $subject, $limit, &$count) {}
function preg_replace_callback($regex, $callback, $subject, $limit, &$count) {}
function preg_filter($regex, $replace, $subject, $limit, &$count) {}
function preg_split($pattern, $subject, $limit, $flags) {}
function preg_quote($str, $delim_char) {}
function preg_grep($regex, $input, $flags) {}
function preg_last_error() {}
