<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension readline 5.4.30
function readline($prompt) {}
function readline_info($varname, $newvalue) {}
function readline_add_history($prompt) {}
function readline_clear_history() {}
function readline_read_history($filename) {}
function readline_write_history($filename) {}
function readline_completion_function($funcname) {}
function readline_callback_handler_install($prompt, $callback) {}
function readline_callback_read_char() {}
function readline_callback_handler_remove() {}
function readline_redisplay() {}
function readline_on_new_line() {}
