<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension shmop
function shmop_open($key, $flags, $mode, $size) {}
function shmop_read($shmid, $start, $count) {}
function shmop_close($shmid) {}
function shmop_size($shmid) {}
function shmop_write($shmid, $data, $offset) {}
function shmop_delete($shmid) {}
