<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension snmp 0.1
function snmpget($host, $community, $object_id, $timeout, $retries) {}
function snmpgetnext($host, $community, $object_id, $timeout, $retries) {}
function snmpwalk($host, $community, $object_id, $timeout, $retries) {}
function snmprealwalk($host, $community, $object_id, $timeout, $retries) {}
function snmpwalkoid($host, $community, $object_id, $timeout, $retries) {}
function snmpset($host, $community, $object_id, $type, $value, $timeout, $retries) {}
function snmp_get_quick_print($d) {}
function snmp_set_quick_print($quick_print) {}
function snmp_set_enum_print($enum_print) {}
function snmp_set_oid_output_format($oid_format) {}
function snmp_set_oid_numeric_print($oid_format) {}
function snmp2_get($host, $community, $object_id, $timeout, $retries) {}
function snmp2_getnext($host, $community, $object_id, $timeout, $retries) {}
function snmp2_walk($host, $community, $object_id, $timeout, $retries) {}
function snmp2_real_walk($host, $community, $object_id, $timeout, $retries) {}
function snmp2_set($host, $community, $object_id, $type, $value, $timeout, $retries) {}
function snmp3_get($host, $sec_name, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $object_id, $timeout, $retries) {}
function snmp3_getnext($host, $sec_name, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $object_id, $timeout, $retries) {}
function snmp3_walk($host, $sec_name, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $object_id, $timeout, $retries) {}
function snmp3_real_walk($host, $sec_name, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $object_id, $timeout, $retries) {}
function snmp3_set($host, $sec_name, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $object_id, $type, $value, $timeout, $retries) {}
function snmp_set_valueretrieval($method) {}
function snmp_get_valueretrieval() {}
function snmp_read_mib($filename) {}
class SNMP{
  public function __construct($version, $host, $community, $timeout, $retries) {}
  public function close() {}
  public function setSecurity($session, $sec_level, $auth_protocol, $auth_passphrase, $priv_protocol, $priv_passphrase, $contextName, $contextEngineID, $param9) {}
  public function get($object_id, $use_orignames) {}
  public function getnext($object_id, $use_orignames) {}
  public function walk($object_id, $suffix_keys, $max_repetitions, $non_repeaters) {}
  public function set($object_id, $type, $value) {}
  public function getErrno() {}
  public function getError() {}
}
class SNMPException extends RuntimeException{
  final private function __clone() {}
  public function __construct($message, $code, $previous) {}
  final public function getMessage() {}
  final public function getCode() {}
  final public function getFile() {}
  final public function getLine() {}
  final public function getTrace() {}
  final public function getPrevious() {}
  final public function getTraceAsString() {}
  public function __toString() {}
}
