<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension sockets
function socket_select(&$read_fds, &$write_fds, &$except_fds, $tv_sec, $tv_usec) {}
function socket_create($domain, $type, $protocol) {}
function socket_create_listen($port, $backlog) {}
function socket_create_pair($domain, $type, $protocol, &$fd) {}
function socket_accept($socket) {}
function socket_set_nonblock($socket) {}
function socket_set_block($socket) {}
function socket_listen($socket, $backlog) {}
function socket_close($socket) {}
function socket_write($socket, $buf, $length) {}
function socket_read($socket, $length, $type) {}
function socket_getsockname($socket, &$addr, &$port) {}
function socket_getpeername($socket, &$addr, &$port) {}
function socket_connect($socket, $addr, $port) {}
function socket_strerror($errno) {}
function socket_bind($socket, $addr, $port) {}
function socket_recv($socket, &$buf, $len, $flags) {}
function socket_send($socket, $buf, $len, $flags) {}
function socket_recvfrom($socket, &$buf, $len, $flags, &$name, &$port) {}
function socket_sendto($socket, $buf, $len, $flags, $addr, $port) {}
function socket_get_option($socket, $level, $optname) {}
function socket_set_option($socket, $level, $optname, $optval) {}
function socket_shutdown($socket, $how) {}
function socket_last_error($socket) {}
function socket_clear_error($socket) {}
function socket_import_stream($stream) {}
function socket_getopt($socket, $level, $optname) {}
function socket_setopt($socket, $level, $optname, $optval) {}
