<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension sysvsem
function sem_get($key, $max_acquire, $perm, $auto_release) {}
function sem_acquire($sem_identifier) {}
function sem_release($sem_identifier) {}
function sem_remove($sem_identifier) {}
