<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension sysvmsg
function msg_get_queue($key, $perms) {}
function msg_send($queue, $msgtype, $message, $serialize, $blocking, &$errorcode) {}
function msg_receive($queue, $desiredmsgtype, &$msgtype, $maxsize, &$message, $unserialize, $flags, &$errorcode) {}
function msg_remove_queue($queue) {}
function msg_stat_queue($queue) {}
function msg_set_queue($queue, $data) {}
function msg_queue_exists($key) {}
