<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension sysvshm
function shm_attach($key, $memsize, $perm) {}
function shm_remove($shm_identifier) {}
function shm_detach($shm_identifier) {}
function shm_put_var($shm_identifier, $variable_key, $variable) {}
function shm_has_var($id, $variable_key) {}
function shm_get_var($id, $variable_key) {}
function shm_remove_var($id, $variable_key) {}
