<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension wddx
function wddx_serialize_value($var, $comment) {}
function wddx_serialize_vars($var_name, $param2) {}
function wddx_packet_start($comment) {}
function wddx_packet_end($packet_id) {}
function wddx_add_vars($packet_id, $var_name, $param3) {}
function wddx_deserialize($packet) {}
