<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension xml
function xml_parser_create($encoding) {}
function xml_parser_create_ns($encoding, $sep) {}
function xml_set_object($parser, &$obj) {}
function xml_set_element_handler($parser, $shdl, $ehdl) {}
function xml_set_character_data_handler($parser, $hdl) {}
function xml_set_processing_instruction_handler($parser, $hdl) {}
function xml_set_default_handler($parser, $hdl) {}
function xml_set_unparsed_entity_decl_handler($parser, $hdl) {}
function xml_set_notation_decl_handler($parser, $hdl) {}
function xml_set_external_entity_ref_handler($parser, $hdl) {}
function xml_set_start_namespace_decl_handler($parser, $hdl) {}
function xml_set_end_namespace_decl_handler($parser, $hdl) {}
function xml_parse($parser, $data, $isfinal) {}
function xml_parse_into_struct($parser, $data, &$values, &$index) {}
function xml_get_error_code($parser) {}
function xml_error_string($code) {}
function xml_get_current_line_number($parser) {}
function xml_get_current_column_number($parser) {}
function xml_get_current_byte_index($parser) {}
function xml_parser_free($parser) {}
function xml_parser_set_option($parser, $option, $value) {}
function xml_parser_get_option($parser, $option) {}
function utf8_encode($data) {}
function utf8_decode($data) {}
