<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension xmlreader 0.1
class XMLReader{
  public function close() {}
  public function getAttribute($name) {}
  public function getAttributeNo($index) {}
  public function getAttributeNs($name, $namespaceURI) {}
  public function getParserProperty($property) {}
  public function isValid() {}
  public function lookupNamespace($prefix) {}
  public function moveToAttributeNo($index) {}
  public function moveToAttribute($name) {}
  public function moveToAttributeNs($name, $namespaceURI) {}
  public function moveToElement() {}
  public function moveToFirstAttribute() {}
  public function moveToNextAttribute() {}
  public function open($URI, $encoding, $options) {}
  public function read() {}
  public function next($localname) {}
  public function readInnerXml() {}
  public function readOuterXml() {}
  public function readString() {}
  public function setSchema($filename) {}
  public function setParserProperty($property, $value) {}
  public function setRelaxNGSchema($filename) {}
  public function setRelaxNGSchemaSource($source) {}
  public function XML($source, $encoding, $options) {}
  public function expand() {}
}
