<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension xmlrpc 0.51
function xmlrpc_encode($value) {}
function xmlrpc_decode($value, $encoding) {}
function xmlrpc_decode_request($xml, &$method, $encoding) {}
function xmlrpc_encode_request($method, $params, $output_options) {}
function xmlrpc_get_type($value) {}
function xmlrpc_set_type(&$value, $type) {}
function xmlrpc_is_fault($arg) {}
function xmlrpc_server_create() {}
function xmlrpc_server_destroy($server) {}
function xmlrpc_server_register_method($server, $method_name, $function) {}
function xmlrpc_server_call_method($server, $xml, $user_data, $output_options) {}
function xmlrpc_parse_method_descriptions($xml) {}
function xmlrpc_server_add_introspection_data($server, $desc) {}
function xmlrpc_server_register_introspection_callback($server, $function) {}
