<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension xmlwriter 0.1
function xmlwriter_open_uri($uri) {}
function xmlwriter_open_memory() {}
function xmlwriter_set_indent($xmlwriter, $indent) {}
function xmlwriter_set_indent_string($xmlwriter, $indentString) {}
function xmlwriter_start_comment($xmlwriter) {}
function xmlwriter_end_comment($xmlwriter) {}
function xmlwriter_start_attribute($xmlwriter, $name) {}
function xmlwriter_end_attribute($xmlwriter) {}
function xmlwriter_write_attribute($xmlwriter, $name, $value) {}
function xmlwriter_start_attribute_ns($xmlwriter, $prefix, $name, $uri) {}
function xmlwriter_write_attribute_ns($xmlwriter, $prefix, $name, $uri, $content) {}
function xmlwriter_start_element($xmlwriter, $name) {}
function xmlwriter_end_element($xmlwriter) {}
function xmlwriter_full_end_element($xmlwriter) {}
function xmlwriter_start_element_ns($xmlwriter, $prefix, $name, $uri) {}
function xmlwriter_write_element($xmlwriter, $name, $content) {}
function xmlwriter_write_element_ns($xmlwriter, $prefix, $name, $uri, $content) {}
function xmlwriter_start_pi($xmlwriter, $target) {}
function xmlwriter_end_pi($xmlwriter) {}
function xmlwriter_write_pi($xmlwriter, $target, $content) {}
function xmlwriter_start_cdata($xmlwriter) {}
function xmlwriter_end_cdata($xmlwriter) {}
function xmlwriter_write_cdata($xmlwriter, $content) {}
function xmlwriter_text($xmlwriter, $content) {}
function xmlwriter_write_raw($xmlwriter, $content) {}
function xmlwriter_start_document($xmlwriter, $version, $encoding, $standalone) {}
function xmlwriter_end_document($xmlwriter) {}
function xmlwriter_write_comment($xmlwriter, $content) {}
function xmlwriter_start_dtd($xmlwriter, $qualifiedName, $publicId, $systemId) {}
function xmlwriter_end_dtd($xmlwriter) {}
function xmlwriter_write_dtd($xmlwriter, $name, $publicId, $systemId, $subset) {}
function xmlwriter_start_dtd_element($xmlwriter, $qualifiedName) {}
function xmlwriter_end_dtd_element($xmlwriter) {}
function xmlwriter_write_dtd_element($xmlwriter, $name, $content) {}
function xmlwriter_start_dtd_attlist($xmlwriter, $name) {}
function xmlwriter_end_dtd_attlist($xmlwriter) {}
function xmlwriter_write_dtd_attlist($xmlwriter, $name, $content) {}
function xmlwriter_start_dtd_entity($xmlwriter, $name, $isparam) {}
function xmlwriter_end_dtd_entity($xmlwriter) {}
function xmlwriter_write_dtd_entity($xmlwriter, $name, $content) {}
function xmlwriter_output_memory($xmlwriter, $flush) {}
function xmlwriter_flush($xmlwriter, $empty) {}
class XMLWriter{
  public function openUri($uri) {}
  public function openMemory() {}
  public function setIndent($indent) {}
  public function setIndentString($indentString) {}
  public function startComment() {}
  public function endComment() {}
  public function startAttribute($name) {}
  public function endAttribute() {}
  public function writeAttribute($name, $value) {}
  public function startAttributeNs($prefix, $name, $uri) {}
  public function writeAttributeNs($prefix, $name, $uri, $content) {}
  public function startElement($name) {}
  public function endElement() {}
  public function fullEndElement() {}
  public function startElementNs($prefix, $name, $uri) {}
  public function writeElement($name, $content) {}
  public function writeElementNs($prefix, $name, $uri, $content) {}
  public function startPi($target) {}
  public function endPi() {}
  public function writePi($target, $content) {}
  public function startCdata() {}
  public function endCdata() {}
  public function writeCdata($content) {}
  public function text($content) {}
  public function writeRaw($content) {}
  public function startDocument($version, $encoding, $standalone) {}
  public function endDocument() {}
  public function writeComment($content) {}
  public function startDtd($qualifiedName, $publicId, $systemId) {}
  public function endDtd() {}
  public function writeDtd($name, $publicId, $systemId, $subset) {}
  public function startDtdElement($qualifiedName) {}
  public function endDtdElement() {}
  public function writeDtdElement($name, $content) {}
  public function startDtdAttlist($name) {}
  public function endDtdAttlist() {}
  public function writeDtdAttlist($name, $content) {}
  public function startDtdEntity($name, $isparam) {}
  public function endDtdEntity() {}
  public function writeDtdEntity($name, $content) {}
  public function outputMemory($flush) {}
  public function flush($empty) {}
}
