<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension xsl 0.1
class XSLTProcessor{
  public function importStylesheet($doc) {}
  public function transformToDoc($doc) {}
  public function transformToUri($doc, $uri) {}
  public function transformToXml($doc) {}
  public function setParameter($namespace, $name, $value) {}
  public function getParameter($namespace, $name) {}
  public function removeParameter($namespace, $name) {}
  public function hasExsltSupport() {}
  public function registerPHPFunctions($restrict) {}
  public function setProfiling($filename) {}
  public function setSecurityPrefs($securityPrefs) {}
  public function getSecurityPrefs() {}
}
