<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension zip 1.11.0
function zip_open($filename) {}
function zip_close($zip) {}
function zip_read($zip) {}
function zip_entry_open($zip_dp, $zip_entry, $mode) {}
function zip_entry_close($zip_ent) {}
function zip_entry_read($zip_entry, $len) {}
function zip_entry_filesize($zip_entry) {}
function zip_entry_name($zip_entry) {}
function zip_entry_compressedsize($zip_entry) {}
function zip_entry_compressionmethod($zip_entry) {}
class ZipArchive{
  public function open($filename, $flags) {}
  public function close() {}
  public function getStatusString() {}
  public function addEmptyDir($dirname) {}
  public function addFromString($name, $content) {}
  public function addFile($filepath, $entryname, $start, $length) {}
  public function addGlob($pattern, $flags, $options) {}
  public function addPattern($pattern, $path, $options) {}
  public function renameIndex($index, $new_name) {}
  public function renameName($name, $new_name) {}
  public function setArchiveComment($comment) {}
  public function getArchiveComment($flags) {}
  public function setCommentIndex($index, $comment) {}
  public function setCommentName($name, $comment) {}
  public function getCommentIndex($index, $flags) {}
  public function getCommentName($name, $flags) {}
  public function deleteIndex($index) {}
  public function deleteName($name) {}
  public function statName($filename, $flags) {}
  public function statIndex($index, $flags) {}
  public function locateName($filename, $flags) {}
  public function getNameIndex($index, $flags) {}
  public function unchangeArchive() {}
  public function unchangeAll() {}
  public function unchangeIndex($index) {}
  public function unchangeName($name) {}
  public function extractTo($pathto, $files) {}
  public function getFromName($entryname, $len, $flags) {}
  public function getFromIndex($index, $len, $flags) {}
  public function getStream($entryname) {}
}
