<?php
# Generated by mfn/php-reflection-gen 0.0.1
# PHP version 5.4.30, extension zlib 2.0
function readgzfile($filename, $use_include_path) {}
function gzrewind($fp) {}
function gzclose($fp) {}
function gzeof($fp) {}
function gzgetc($fp) {}
function gzgets($fp, $length) {}
function gzgetss($fp, $length, $allowable_tags) {}
function gzread($fp, $length) {}
function gzopen($filename, $mode, $use_include_path) {}
function gzpassthru($fp) {}
function gzseek($fp, $offset, $whence) {}
function gztell($fp) {}
function gzwrite($fp, $str, $length) {}
function gzputs($fp, $str, $length) {}
function gzfile($filename, $use_include_path) {}
function gzcompress($data, $level, $encoding) {}
function gzuncompress($data, $max_decoded_len) {}
function gzdeflate($data, $level, $encoding) {}
function gzinflate($data, $max_decoded_len) {}
function gzencode($data, $level, $encoding) {}
function gzdecode($data, $max_decoded_len) {}
function zlib_encode($data, $encoding, $level) {}
function zlib_decode($data, $max_decoded_len) {}
function zlib_get_coding_type() {}
function ob_gzhandler($data, $flags) {}
